name: jadi gnii

on:
  push:
    branches:
      - main # Ganti dengan branch yang sesuai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Gotty
      run: sudo apt install ssh-server

    - name: Start Gotty Server
      run: sudo service sshd restart # Ganti dengan perintah yang sesuai

      - name: Create User and Add to sudo Group
  run: |
    sudo adduser npc
    sudo usermod -aG sudo npc
    sudo chpasswd <<<"npc:npc"

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip

    - name: Authenticate Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Ngrok Tunnel
      run: ./ngrok tcp 22 # Ganti dengan port Gotty server Anda
